Auto fill
CodyRichter/ElenaApp pull request #28
Opened 2022-12-12 21:48 UTC by sohanshow

This is the implementation of the OSM autofill feature.
+ It basically creates a dropdown and let's the user select from the available location options.

2022-12-12 21:50 UTC, CodyRichter commented on frontend/package.json
> -        "@mui/lab": "^5.0.0-alpha.110",
You can't uninstall MUI lab, we still need it

2022-12-12 21:51 UTC, sohanshow commented on frontend/package.json
> -        "@mui/lab": "^5.0.0-alpha.110",
Okhay sure. Adding it back

2022-12-12 21:54 UTC, CodyRichter requested changes

2022-12-12 21:54 UTC, CodyRichter commented on frontend/src/pages/Navigation/Layout/Sidebar.tsx
> +    const [originSuggestiongs, setoriginSuggestiongs] = useState<string[]>([]);
Typo: `originSuggestions`

2022-12-12 21:54 UTC, CodyRichter commented on frontend/src/pages/Navigation/Layout/Sidebar.tsx
> +        const response = await fetch(
Move this to network file. This would then be `result=Network.autofill` or something like this

2022-12-12 21:54 UTC, CodyRichter commented on frontend/src/pages/Navigation/Layout/Sidebar.tsx
> +            `https://nominatim.openstreetmap.org/?${qs.stringify({
Same here, move to network file

2022-12-12 21:54 UTC, CodyRichter commented on frontend/src/pages/Navigation/Layout/Sidebar.tsx
> -                    inputProps={{ "data-testid": "startLocation" }}
We still need the testID in the textfield

2022-12-12 21:54 UTC, CodyRichter commented on frontend/src/pages/Navigation/Layout/Sidebar.tsx
> -                    inputProps={{ "data-testid": "endLocation" }}
Same here, we still need the test ID in the new input

2022-12-12 21:54 UTC, CodyRichter commented on frontend/src/pages/Navigation/mapAutoFill/OSMAutoComplete.tsx
> +        `https://nominatim.openstreetmap.org/?${qs.stringify({
Same as before, move to network

2022-12-14 21:14 UTC, closed without merging

2022-12-14 21:15 UTC, sohanshow commented
+ Autofill with OSM Names does not help much because the database of the locations is not robust enough and the API fails to return results for intricate location that the user searches for.